#!/bin/sh

source $HOME/dotfiles/sketchybar/plugins/palette.sh

PLUGIN_DIR="$HOME/dotfiles/sketchybar/plugins"
ITEM_DIR="$HOME/dotfiles/sketchybar/items"

sketchybar --bar height=48 \
    position=top \
    padding_left=10 \
    padding_right=10 \
    color=0x00ffffff

sketchybar --default icon.font="Maple Mono:Semibold:15.0" \
    icon.color=${PALETTE4} \
    label.font="Maple Mono:Semibold:15.0" \
    label.color=${PALETTE4} \
    background.color=${PALETTE1} \
    background.corner_radius=8 \
    background.height=30 \
    padding_left=0 \
    padding_right=10 \
    label.padding_left=4 \
    label.padding_right=10 \
    icon.padding_left=13 \
    icon.padding_right=12

# Left items
source ${ITEM_DIR}/spaces.sh

source ${ITEM_DIR}/front_app.sh

# Middle items
# source $ITEM_DIR/media.sh

# Right items
source ${ITEM_DIR}/calendar.sh
source ${ITEM_DIR}/volume.sh
source ${ITEM_DIR}/battery.sh
source ${ITEM_DIR}/cpu.sh

sketchybar --update
