#!/bin/bash

# save_current() {
#     grep 'cpu ' /proc/stat > /tmp/cpustat
# }
# [ ! -e /tmp/cpustat ] && save_current
# previous=$(cat /tmp/cpustat)
# current=$(grep 'cpu ' /proc/stat)
# awkscript='NR == 1 {
#              owork=($2+$4);
#              oidle=$5;
#            }
#            NR > 1 {
#              work=($2+$4)-owork;
#              idle=$5-oidle;
#              printf "%.2f", 100 * work / (work+idle)
#            }'

cpu_idle=$(mpstat -P ALL | grep "all"  | sed 's/.* \(.*\),\(.*\)/\1/')
cpu_usage=$((100 - $cpu_idle))
# cpu_usage=$((100 - cpu_idle))
# cpu_usage=$(echo $((100 - $(mpstat -P ALL | grep "all"  | sed 's/.* \(.*\),\(.*\)/\1.\2/'))) | sed 's/\(....\)/\1/')
# echo $cpu_usage

# usage=$(echo -e "$previous\n$current" | awk "$awkscript")
# save_current
# if (( $(echo "$usage > 10.0" |bc -l) )); then
#     usage=$(LC_NUMERIC="en_US.UTF-8" printf "%0.1f\n" $usage)
# fi

memory=($(free -t | grep Mem:))
memory_used=$(echo "${memory[2]} / ${memory[1]} * 100" | bc -l)
memory_used=$(LC_NUMERIC="en_US.UTF-8" printf "%0.0f\n" $memory_used)

echo "  $cpu_usage% $memory_used% "
