#!/usr/bin/env bash

set -x


# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
# yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"

#/Users/termanteus/.config/yabai/create_spaces.sh
# $HOME/dotfiles/yabai/create_spaces.sh

# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
#################### Status bar ####################
# SPACEBAR_HEIGHT=34
# yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

yabai -m config                                                     \
    mouse_follows_focus             on                              \
    window_placement                second_child                    \
    window_shadow                   off                             \
    window_opacity                  on                              \
    insert_feedback_color           0xE02d74da                      \
    split_ratio                     0.50                            \
    auto_balance                    off                             \
    mouse_modifier                  fn                              \
    mouse_action1                   move                            \
    mouse_action2                   resize                          \
    mouse_drop_action               swap                            \
    top_padding                     15                              \
    bottom_padding                  15                              \
    left_padding                    15                              \
    right_padding                   15                              \
    window_gap                      15

yabai -m config layout bsp

# ===== Rules ==================================
# ===== Rules ==================================
yabai -m rule --add app="^Bartender" manage=off
yabai -m rule --add app="Unity" manage=off
yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add app="^(LuLu|Vimac|Calculator|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|IINA)$" manage=off
yabai -m rule --add label="Steam" app="^Steam$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Alfred" app="^Alfred$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

# ===== Signals ================================

# yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=display_changed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_created action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_destroyed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_focused action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_title_changed action="${ubersicht_spaces_refresh_command}"

focus_window () {
    SPACE_NAME=$(yabai -m query --spaces --space | jq ".label")
    WINDOW_ID=$(yabai -m query --windows --space | jq ".[] | select (.app=${SPACE_NAME}).id")
    yabai -m window --focus "${WINDOW_ID}"
}

# focus window after active space changes
yabai -m signal --add event=space_changed action="focus_window"

# focus window after active display changes
yabai -m signal --add event=display_changed action="focus_window"

set +x
printf "yabai: configuration loaded...\\n"

borders active_color=0xff81A1C1 inactive_color=0xff4C566A width=4.0 hidpi=on &
