#!/bin/bash
# Tiny colored fetch script
# Requires Typicons Font to display the icons
# elenapan @ github

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'

# Items
sep=
s=$d$f0$sep$t

w='wi'
CURRENT_WIFI="$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I)"
wifiname="$(echo "$CURRENT_WIFI" | grep -o "SSID: .*" | sed 's/^SSID: //')"

h='wm'
wmname="aqua"

k='kr'
kernel="$(uname -r | cut -d '-' -f1)"

sh='sh'
shell=$(basename $SHELL)

# (\ /)
# ( . .)
# c(")(")

tput clear
cat << EOF
           $d$f1$h   $t$wmname
 (\ /)     $f3$k   $t$kernel
 ( $d. .$t)    $f2$sh   $t$shell
 c($f1"$t)($f1"$t)   $f4$w   $t$wifiname

EOF

# cat << EOF
#            $d$f1$h    $t$wmname
#  $f3(\ /)     3$k   $t$kernel
#  $f2( . .)    $f2$sh    $t$shell
#  c$f4(")(")   $r    $t$uptime
#            $f5$w  $t$wifiname
#
# EOF
